#!/bin/bash

declare -i time_control_notifs=2000

case "$1" in
    --kbhi)
    declare mode=$(asusctl -k | tail -n 1 | cut -d " " -f 5 |  tr '[:upper:]' '[:lower:]')
    case "$mode" in
        off) mode="low";;
        low) mode="med";;
        med) mode="high";;
        *) mode="high";;
    esac
    notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Keyboard backlight ${mode}"
    asusctl -k "${mode}"
    ;;
    --kblo)
    declare mode=$(asusctl -k | tail -n 1 | cut -d " " -f 5 |  tr '[:upper:]' '[:lower:]')
    case "$mode" in
        low) mode="off";;
        med) mode="low";;
        high) mode="med";;
        *) mode="off";;
    esac
    notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Keyboard backlight ${mode}"
    asusctl -k "${mode}"
    ;;
    --rog)
    rog-control-center
    ;;
    --kbch) 
    asusctl aura -n && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Keyboard led mode changed"
    ;;
    --pro)
    asusctl profile -n && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "$(asusctl profile -p | tail -1)"
    ;;
esac
