#!/bin/bash

declare -i time_control_notifs=2000
declare brightness

case "$1" in
    -d)
    brillo -q -U $2 -u 1000;
    brightness=$(python -c "print(round($(brillo -G)))")
    ;;
    -i)
    brillo -q -A $2 -u 1000;
    ;;
esac

brightness=$(python -c "print(round($(brillo -G)))")
notify-send -t ${time_control_notifs} -h string:x-dunst-stack-tag:settings_notif -h int:value:$(brillo -G) "Brightness: ${brightness}";

