#!/bin/bash

XCURSOR_SIZE=16
declare -i time_control_notifs=2000

mkdir -p $HOME/Pictures/Screenshots
mkdir -p /tmp/grimblast

declare active_opacity=$(hyprctl getoption "decoration:active_opacity" | head -n 1 | cut -d " " -f 2)
declare inactive_opacity=$(hyprctl getoption "decoration:inactive_opacity" | head -n 1 | cut -d " " -f 2)
declare fullscreen_opacity=$(hyprctl getoption "decoration:fullscreen_opacity" | head -n 1 | cut -d " " -f 2)
declare dim_inactive=$(hyprctl getoption "decoration:dim_inactive" | head -n 1 | cut -d " " -f 2)
declare drop_shadow=$(hyprctl getoption "decoration:drop_shadow" | head -n 1 | cut -d " " -f 2)
declare blur=$(hyprctl getoption "blur:enabled" | head -n 1 | cut -d " " -f 2)

hyprctl keyword "decoration:active_opacity" 1.0
hyprctl keyword "decoration:inactive_opacity" 1.0
hyprctl keyword "decoration:dim_inactive" false
hyprctl keyword "decoration:drop_shadow" false
hyprctl keyword "blur:enabled" false

case "$1" in
    -s)
    grimblast copysave screen $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -a)
    grimblast copysave area $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -w)
    grimblast copysave active $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -e) 
    grimblast copysave area "/tmp/grimblast/tmp.png" && tesseract  -l eng "/tmp/grimblast/tmp.png" - | wl-copy && rm "/tmp/grimblast/tmp.png" && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "OCR copied"
    ;;
    -h) 
    grimblast copysave area "/tmp/grimblast/tmp.png" && tesseract  -l hin "/tmp/grimblast/tmp.png" - | wl-copy && rm "/tmp/grimblast/tmp.png" && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "OCR copied"
    ;;
esac

hyprctl keyword "decoration:active_opacity" ${active_opacity}
hyprctl keyword "decoration:inactive_opacity" ${inactive_opacity}
hyprctl keyword "decoration:fullscreen_opacity" ${fullscreen_opacity}
hyprctl keyword "decoration:dim_inactive" ${dim_inactive}
hyprctl keyword "decoration:drop_shadow" ${drop_shadow}
hyprctl keyword "blur:enabled" ${blur}
