#!/bin/bash

declare -i time_control_notifs=2000
declare volume_percent
declare volume

case "$1" in
-i)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    wpctl set-volume @DEFAULT_AUDIO_SINK@ $2%+
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 2 -d ' ')
    volume_percent=$(python -c "print(round(100 * ${volume}))")
    notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif -h int:value:${volume_percent} "Volume: ${volume_percent}"
    ;;
-d)
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 2 -d ' ')
    volume_percent=$(python -c "print(round(100 * ${volume}))")
    if [[ $volume_percent -le $2 ]] || [[ $volume_percent -eq 0 ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 1
        wpctl set-volume @DEFAULT_AUDIO_SINK@ $2%-
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Volume: muted"
        exit 0
    fi
    wpctl set-volume @DEFAULT_AUDIO_SINK@ $2%-
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 2 -d ' ')
    volume_percent=$(python -c "print(round(100 * ${volume}))")
    notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif -h int:value:${volume_percent} "Volume: ${volume_percent}"
    ;;
-m)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

    if [[ $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 3 -d ' ' | wc -c) > 2 ]]; then
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Volume: muted"
    else
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Volume: unmuted"
    fi
    ;;

esac
