#!/usr/bin/bash

## All the assumptions
k_path="/boot"
efi_path="/boot/EFI"
uki_path="/boot/EFI/Linux"
keys_path="/usr/share/keys"
cmdline_path="/usr/share/cmdline"

__help="
Usage: $(basename $0) [OPTIONS] [Arguments]

Options:
    -s      : --sign
    -g      : --generate
Arguments:
-s|--sign:
            -b      : boot   
                    : bootloader
            -k      : kernel-image
            -u      : uki
                    : unified-kernel-image

Note: This Uses sbsign Program

-g|--generate:
            -i      : initramfs
            -u      : uki
                    : unified-kernel-image

Note: This Uses mkinitcpio Program
"

case "$1" in
    -s|--sign)
        case "$2" in
            -b|boot|bootloader)
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${efi_path}/BOOT/BOOTx64.EFI ${efi_path}/BOOT/BOOTx64.EFI
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${efi_path}/systemd/systemd-bootx64.efi ${efi_path}/systemd/systemd-bootx64.efi

            ;;
            -k|kernel-image)
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${k_path}/vmlinuz-linux ${k_path}/vmlinuz-linux;
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${k_path}/vmlinuz-linux-stable ${k_path}/vmlinuz-linux-stable 
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${k_path}/vmlinuz-linux-g14 ${k_path}/vmlinuz-linux-g14;
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${k_path}/vmlinuz-linux-g14-stable ${k_path}/vmlinuz-linux-g14-stable
            ;;
            -u|uki|unified-kernel-image)
                sudo sbsign --key ${keys_path}/db.key \
                            --cert ${keys_path}/db.crt \
                            --output ${uki_path}/uki-g14.efi ${uki_path}/uki-g14.efi
            ;;
            *)
                echo "$__help"
            ;;
        esac
    ;;
    -g|--generate)
        case "$2" in
            -i|initramfs)
                sudo mkinitcpio -p linux;
                sudo mkinitcpio -p linux-g14;
            ;;
            -u|uki|unified-kernel-image)
                sudo mkinitcpio -p linux-g14 -- \
                                --uefi ${uki_path}/uki-g14.efi \
                                --cmdline ${cmdline_path}/cmdline
            ;;
            *)
            echo "$__help"
            ;;
        esac
    ;;
    *)
        echo "$__help"
    ;;
esac

