#!/bin/bash

declare -l time_control_notifs=2000

mkdir -p $HOME/Pictures/Screenshots
mkdir -p /tmp/grimshot 
case "$1" in
    -s)
    grimshot savecopy screen $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:screenshot_notif "Screenshot saved"
    ;;
    -a)
    grimshot savecopy area $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:screenshot_notif "Screenshot saved"
    ;;
    -c) 
    grimshot savecopy area "/tmp/grimshot/tmp.png" && tesseract -l eng "/tmp/grimshot/tmp.png" - | wl-copy && rm "/tmp/grimshot/tmp.png" && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:screenshot_notif "OCR copied"
esac
