#!/bin/bash

XCURSOR_SIZE=16
declare -l time_control_notifs=2000

mkdir -p $HOME/Pictures/Screenshots
mkdir -p /tmp/grimblast

hyprctl keyword "decoration:active_opacity" 1.0
hyprctl keyword "decoration:inactive_opacity" 1.0
hyprctl keyword "decoration:drop_shadow" false
hyprctl keyword "decoration:dim_inactive" false
hyprctl keyword "blur:enabled" false

case "$1" in
    -s)
    grimblast copysave screen $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -a)
    grimblast copysave area $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -w)
    grimblast copysave active $HOME/Pictures/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "Screenshot saved"
    ;;
    -e) 
    grimblast copysave area "/tmp/grimblast/tmp.png" && tesseract  -l eng "/tmp/grimblast/tmp.png" - | wl-copy && rm "/tmp/grimblast/tmp.png" && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "OCR copied"
    ;;
    -h) 
    grimblast copysave area "/tmp/grimblast/tmp.png" && tesseract  -l hin "/tmp/grimblast/tmp.png" - | wl-copy && rm "/tmp/grimblast/tmp.png" && \
        notify-send -t $time_control_notifs -h string:x-dunst-stack-tag:settings_notif "OCR copied"
    ;;
esac

hyprctl keyword "decoration:active_opacity" 0.90
hyprctl keyword "decoration:inactive_opacity" 0.90
hyprctl keyword "decoration:drop_shadow" true
hyprctl keyword "decoration:dim_inactive" true
hyprctl keyword "blur:enabled" true
