#!/bin/sh
#xrandr --dpi 192 --output eDP --primary --mode 2560x1440 --scale 0.66 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off --output DP-6 --off --output DP-7 --off --output DP-8 --off
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
