alias cls="clear -x"
alias ls="ls -F --color=auto"
alias cd.="cd .."

alias dmpv="devour mpv"
alias dimvr="devour imvr"
alias dnemo="devour nemo"

alias yt="ytfzf -stlN --preview-side=right --silent"
alias yth="ytfzf -tlHN --preview-side=right --silent"
alias yts="ytfzf -tlSN --preview-side=right --silent"
alias ytss="ytfzf -tlSN --sort --filter-id=EgIIAg --preview-side=right --silent"
alias ytd="ytfzf -tldN --preview-side=right"
alias ytt="ytfzf -tlTN --preview-side=right --silent"
alias yttg="ytfzf -tlN --preview-side=right --trending=gaming --silent"
alias yttm="ytfzf -tlN --preview-side=right --trending=movies --silent"
alias ytm="ytfzf -mlDN --silent"
alias ytmt="ytfzf -mlDN --trending=music --silent"
alias ytmd="ytfzf -mldDN silent"
