theme = "gruvbox-dark"
icons = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "net"
format = "{ssid} {signal_strength}"
format_alt = "{ip} {speed_up;K*b} {speed_down;K*b}"

[[block]]
block = "backlight"

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %b %d"

[[block]]
block = "time"
interval = 5
format = "%T"

[[block]]
block = "notify"

