require("impatient").enable_profile()

require("plugins.all-plugins")
require("plugins.lualine")
require("plugins.dashboard")
require("plugins.treesitter")
require("plugins.orgmode")
require("plugins.telescope-git")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.sniperun")
require("plugins.trouble")
require("plugins.dap")
